* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1347_SYSTCALL .
CLASSPOOL_NAME CLASSPOOL_SYSTEM_CALL .
method IF_IFPOOL_SYSTEM_CALL~IF_METH_SYSTEM_CALL_KO2.
  DATA f1     TYPE C VALUE 'Z'.
  DATA f2(80) TYPE C VALUE 'CLASSPOOL_SYSTEM_CALL'.
  DATA f3(80)  TYPE C VALUE 'if_ifpool_system_call~if_meth_system_call_ko2'. 
  DATA f4(5)  TYPE C VALUE 'FCT'. 
  
  SYSTEM-CALL CHECK f1 FOR SEQUENCE OF C CLASS f2 METHOD f3 PARAMETER f4.
  
ENDMETHOD.
