* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1347_SYSTCALL .
USER_EXIT_NAME ZX001_SYSTEM_CALL .

MODULE MOD_SYSTEM_CALL_KO1 OUTPUT.
  SYSTEM-CALL OBJMGR PERFORM MARK.
   
ENDMODULE. 

MODULE MOD_SYSTEM_CALL_KO2 OUTPUT.
  SYSTEM-CALL OBJMGR PERFORM GARBAGE COLLECTION.
   
ENDMODULE. 

MODULE MOD_SYSTEM_CALL_KO3 OUTPUT.
  DATA ref2  TYPE REF TO DATA.
  CLASS CLASSPOOL_SYSTEM_CALL DEFINITION LOAD.
  CREATE OBJECT oref TYPE CLASSPOOL_SYSTEM_CALL.
  
  SYSTEM-CALL OBJMGR GET STATE OF oref INTO ref2.
   
ENDMODULE.

MODULE MOD_SYSTEM_CALL_KO4 OUTPUT. 
  DATA f3  TYPE i.
  CLASS CLASSPOOL_SYSTEM_CALL DEFINITION LOAD.
  CREATE OBJECT oref TYPE CLASSPOOL_SYSTEM_CALL.
  
  SYSTEM-CALL EVENTS GET NUM_HANDLERS FOR event_system_call OF INST oref INTO f3.
  
ENDMODULE.
  