* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1813_SYSUBRCAUTHCHK .
BADI_NAME BADICLASSPOOL_AUTHORITYCHECK .
method IF_BADI_IFPOOL_AUTHORITYCHECK~IF_BADI_METH_AUTHORITYCHECK_KO1.

  AUTHORITY-CHECK OBJECT 'S_CARRID'
                  ID 'CARRID' FIELD DUMMY
                  ID 'ACTVT'  FIELD '03'.

ENDMETHOD.
