* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1813_SYSUBRCAUTHCHK .
CLASSPOOL_NAME CLASSPOOL_AUTHORITYCHECK .
METHOD SEND_EVENT_AUTHORITYCHECK_KO2.

  RAISE EVENT EVENT_AUTHORITYCHECK_KO2
        EXPORTING I_MESSAGE = SY-SUBRC.
ENDMETHOD.
