* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1813_SYSUBRCAUTHCHK .
USER_EXIT_NAME ZX001_AUTHORITYCHECK .

MODULE MOD_AUTHORITYCHECK_KO1 OUTPUT.
  AUTHORITY-CHECK OBJECT 'S_CARRID'
                  ID 'CARRID' DUMMY
                  ID 'ACTVT'  FIELD '03'.
   
ENDMODULE. 
  