* extractor_prog_Version 6.0 for SAP 4.7, ECC5, ECC6.
* DATE 20081027 .
* SAP_Version 700 .
* PROGRAM_STATUS SYSTEM . Dev_Class Z1355_BAPINRAISE .
INCLUDE_NAME INC_BAPI_RAISE_TO_ABORT_UXX .
*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE INC_BAPI_RAISE_TO_ABORT_U01.
                    "FCT_BAPI_NOT_RAISE_KO1
INCLUDE INC_BAPI_RAISE_TO_ABORT_U02.
                    "FCT_BAPI_NOT_RAISE_KO2
INCLUDE INC_BAPI_RAISE_TO_ABORT_U03.
                    "FCT_BAPI_NOT_RAISE_KO3
INCLUDE INC_BAPI_RAISE_TO_ABORT_U04.
                    "FCT_BAPI_NOT_RAISE_OK1
INCLUDE INC_BAPI_RAISE_TO_ABORT_U05.
                    "FCT_BAPI_NOT_RAISE_OK2
