* extractor_prog_Version 6.2 for SAP 4.7, ECC5, ECC6.
* DATE 20090422 .
* SAP_Version 700 .
* Dev_Class Z1728_WDPNCHNCTRLFLOW .
REPORT SAP_REPORT_CHANGE_PROG_FLOW1 .

SELECTION-SCREEN BEGIN OF SCREEN 1000 AS WINDOW.
 SELECTION-SCREEN BEGIN OF BLOCK SEL1 WITH FRAME.
  PARAMETERS: AU_LNAME(40) TYPE C,
              AU_FNAME(40) TYPE C.
 SELECTION-SCREEN END OF BLOCK SEL1.
SELECTION-SCREEN END OF SCREEN 1000.
SELECTION-SCREEN SKIP.
START-OF-SELECTION.
    LEAVE PROGRAM.

