* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1803_SYNCHK .
BADI_NAME BADICLASSPOOL_SYNTAX_CHECK .
method CLASS_CONSTRUCTOR.
  SET EXTENDED CHECK OFF.
  
  WRITE: / 'SYNTAX CHECK DISABLED'.
ENDMETHOD.
  