* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1803_SYNCHK .
CLASSPOOL_NAME CLASSPOOL_SYNTAX_CHECK .

METHOD SEND_EVENT_SYNTAX_CHECK_KO2.

  RAISE EVENT EVENT_SYNTAX_CHECK_KO2
        EXPORTING I_MESSAGE = SY-SUBRC.
ENDMETHOD.
