* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1340_HRESPCLASS.
BADI_NAME BADICLASSPOOL_HIGH_RFC .
method IF_BADI_IFPOOL_HIGH_RFC~IF_BADI_METH_HIGH_RFC_2.
  WRITE: / 'BADI CLASS INTERFACE METHODE 2'.  
ENDMETHOD.
