* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1340_HRESPCLASS.
CLASSPOOL_NAME CLASSPOOL_HIGH_RFC_SUPER .
method IF_IFPOOL_HIGH_RFC_SUPER~IF_METH_HIGH_RFC_SUPER_1.
  WRITE: / 'IMPLEMENTED FROM SUPER CLASS INTERFACE'.

ENDMETHOD.
