* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1340_HRESPCLASS.
CLASSPOOL_NAME CLASSPOOL_HIGH_RFC_KO1 .

METHOD ON_EVENT_HIGH_RFC_KO1_1 .
	WRITE: / 'EVENT IN INHERITED CLASS IS TRIGGERED'.
            
ENDMETHOD.
