* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1340_HRESPCLASS .
CLASSPOOL_NAME CLASSPOOL_HIGH_RFC_KO1 .
method MET_HIGH_RFC_BADI_KO1_2.
  WRITE: / 'CALL TO BADI INTERFACE METHOD IF_BADI_IFPOOL_HIGH_RFC~IF_BADI_METH_HIGH_RFC_2'.
  
  CALL METHOD BadiRef->IF_BADI_IFPOOL_HIGH_RFC~IF_BADI_METH_HIGH_RFC_2.
ENDMETHOD.
