* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1814_SYUNAM .
BADI_NAME BADICLASSPOOL_SY_UNAME .

METHOD ON_BADI_EVENT_SY_UNAME_KO5 .

  IF SY-UNME EQ 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME.
  ENDIF.  
ENDMETHOD.
