* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1814_SYUNAM .
BADI_NAME BADICLASSPOOL_SY_UNAME .

METHOD SEND_BADI_EVENT_SY_UNAME_KO4 .

  RAISE EVENT BADI_EVENT_SY_UNAME_KO4
        EXPORTING I_MESSAGE = SY-UNAME.
ENDMETHOD.
