* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1814_SYUNAM .
BADI_NAME BADICLASSPOOL_SY_UNAME .

method IF_BADI_IFPOOL_SY_UNAME~IF_BADI_METH_SY_UNAME_KO3.

DATA BOOL TYPE C VALUE '1'.

IF BOOL = 1.
    WRITE: / 'BOOL =', BOOL.
    
  ELSEIF SY-UNAME = 'JOHN DOE'.
    WRITE: / 'SY-UNAME =', SY-UNAME.
ENDIF.


ENDMETHOD.