* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1814_SYUNAM .
USER_EXIT_NAME ZX001_SY_UNAME .

MODULE MOD_SY_UNAME_KO1 OUTPUT.
  IF SY-UNAME CO 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF. 
ENDMODULE. 
  
MODULE MOD_SY_UNAME_KO2 OUTPUT.
  IF SY-UNAME CN 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF.
ENDMODULE.   
 
MODULE MOD_SY_UNAME_KO3 OUTPUT.
  IF SY-UNAME CA 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF. 
ENDMODULE.   

MODULE MOD_SY_UNAME_KO4 OUTPUT.
  IF SY-UNAME NA 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF. 
ENDMODULE.  
 
MODULE MOD_SY_UNAME_KO5 OUTPUT.
  IF SY-UNAME NS 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF. 
ENDMODULE.   

MODULE MOD_SY_UNAME_KO6 OUTPUT.
  IF SY-UNAME CP '*JOHN DOE*'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF. 
ENDMODULE.  
 
MODULE MOD_SY_UNAME_KO7 OUTPUT.
  IF SY-UNAME NP '*JOHN DOE*'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF.
ENDMODULE.

MODULE MOD_SY_UNAME_KO8 OUTPUT.
  IF SY-UNAME CS 'JOHN DOE'.
    WRITE: / 'SY-UNAME=', SY-UNAME. 
  ENDIF.
ENDMODULE.
      