* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1676_SYSUBRCDS .
BADI_NAME BADICLASSPOOL_OPEN_READ_DATASET .
method IF_BADI_IFPOOL_OPEN_READ_DATASET~IF_BADI_METH_OPEN_READ_DATASET_KO1.

   OPEN DATASET file FOR INPUT IN TEXT MODE ENCODING DEFAULT.
   
   READ DATASET file INTO RESULT
   WHILE SY-SUBRC = 0.
      READ DATASET file INTO result.
      WRITE: / result.
   ENDWHILE.
   
   CLOSE DATASET file.

ENDMETHOD.
