* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1676_SYSUBRCDS .
BADI_NAME BADICLASSPOOL_AUTHORITYCHECK .

METHOD ON_BADI_EVENT_AUTHORITYCHECK_KO2 .

  AUTHORITY-CHECK OBJECT 'S_CARRID'
                  ID 'CARRID' FIELD DUMMY
                  ID 'ACTVT'  FIELD '03'.
ENDMETHOD.

METHOD SEND_BADI_EVENT_AUTHORITYCHECK_KO2 .

  RAISE EVENT BADI_EVENT_AUTHORITYCHECK_KO2
        EXPORTING I_MESSAGE = SY-SUBRC.
ENDMETHOD.
