* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1676_SYSUBRCDS .
CLASSPOOL_NAME BADICLASSPOOL_AUTHORITYCHECK .
method CLASS_CONSTRUCTOR.

  AUTHORITY-CHECK OBJECT 'S_CARRID'
                  ID 'CARRID' FIELD DUMMY
                  ID 'ACTVT'  FIELD '03'.
ENDMETHOD.
  
method CONSTRUCTOR.

  AUTHORITY-CHECK OBJECT 'S_CARRID'
                  ID 'CARRID' FIELD DUMMY
                  ID 'ACTVT'  FIELD '03'.
ENDMETHOD.
