* extractor_prog_Version 6.3.1 for SAP ECC5, ECC6.
* DATE 20090930 .
* SAP_Version 700 .
* Dev_Class Z1676_SYSUBRCDS .
CLASSPOOL_NAME CLASSPOOL_OPEN_READ_DATASET .
METHOD SEND_EVENT_OPEN_READ_DATASET_KO2.

  RAISE EVENT EVENT_OPEN_READ_DATASET_KO2
        EXPORTING I_MESSAGE = SY-SUBRC.
ENDMETHOD.
